# Generated by Django 6.0.2 on 2026-02-07 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=150, verbose_name='F.I.Sh')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Telefon')),
                ('position', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Lavozim')),
                ('department', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Bo‘lim')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='employees/avatars/')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['is_active', 'full_name'], name='core_employ_is_acti_bbea3c_idx'), models.Index(fields=['department', 'is_active'], name='core_employ_departm_67517c_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.PositiveIntegerField(db_index=True, verbose_name='Qurilma ID')),
                ('timestamp', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Qayd vaqti')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.employee', verbose_name='Xodim')),
            ],
            options={
                'verbose_name': 'Ish vaqti',
                'verbose_name_plural': 'Ish vaqtlari',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['employee', 'created_at'], name='core_employ_employe_8c539d_idx'), models.Index(fields=['device_id', 'created_at'], name='core_employ_device__ba4395_idx'), models.Index(fields=['timestamp'], name='core_employ_timesta_8678b6_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'timestamp'), name='uniq_employee_timestamp')],
            },
        ),
    ]
