# Generated by Django 6.0.2 on 2026-02-08 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Email'),
        ),
    ]
